// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NCode: typeof import('naive-ui')['NCode']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NPopover: typeof import('naive-ui')['NPopover']
  }
}
