export { Mafs } from './components/mafs'
export { CartesianCoordinates } from './components/cartesianCoordinates'
export { PlotOfx } from './components/plot'
export { Point } from './components/point'
export { Text } from './components/text'
export { Line } from './components/line'
export { MovablePoint } from './components/point'